
from .base import Component as TODO
from .dialogbody import DialogBody

component_classes = {
    'action': TODO,
    'actionList': TODO,
    'body': DialogBody,
    'button': TODO,
    'changeGuardInteractive': TODO,
    'checkBox': TODO,
    'checkList': TODO,
    'comboBox': TODO,
    'dateControl': TODO,
    'eventInteractive': TODO,
    'htmlArea': TODO,
    'image': TODO,
    'label': TODO,
    'list': TODO,
    'listBox': TODO,
    'menuItem': TODO,
    'numberControl': TODO,
    'panel': TODO,
    'popupMenu': TODO,
    'progressBar': TODO,
    'radioBox': TODO,
    'radioButton': TODO,
    'radioGroup': TODO,
    'separator': TODO,
    'splitPane': TODO,
    'tabbedPane': TODO,
    'table': TODO,
    'textArea': TODO,
    'textField': TODO,
    'tree': TODO,
    'upDown': TODO,
    'valueInteractive': TODO,
    'view': TODO,
}
